name: CI
 
on:
  pull_request:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.3.0'
          
      - name: Install npm
        run: npm install -g npm@6
 
      - name: Install dependencies
        run: npm install --no-package-lock
 
      - name: Lint code
        run: npm run lint